### ISSUE TITLE
Not able to compile with zksolc

### ISSUE THREAD

**Issue by web3dopamine** [SKYBITDev3/SKYBIT-Keyless-Deployment#1]
I am not able to generate articles for zksync which should be folder `artifacts-zk` and due with which i am getting the following error: 

`ProviderError: Failed to serialize transaction: toAddressIsNull`

not sure how to resolve this

**Comment by SKYBITDev3** [comment]
I apologize for the late response, I've been busy.

I believe zksync isn't fully EVM-equivalent, so some things that work on Ethereum and fully EVM-equivalent blockchains may not work on zksync.

Have you managed to solve your problem?

**Comment by web3dopamine** [comment]
Unfortunately, i havent able to solve my issue.

Can you confirm that SKYBIT works on zksync?

**Comment by SKYBITDev3** [comment]
I had a quick look and all that was required was to add `to` into the transaction data, at
https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/blob/588ac72827c871eddce60bb2f06c59c176518818/scripts/keyless-deploy-functions.js#L83 and https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/blob/588ac72827c871eddce60bb2f06c59c176518818/scripts/keyless-deploy-functions.js#L106

I also found that on zksync the gas cost to deploy is around 230000, so the gas limit at https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment/blob/588ac72827c871eddce60bb2f06c59c176518818/scripts/deployKeylessly-Create3Factory.js#L73 would need to be increased from 100k, e.g. to 250k. On most other EVM blockchains 100k is more than enough.

Both of these would cause addresses to be different, so you'd need to do these changes before you deploy to any mainnets, then never change these again.
