### ISSUE TITLE
2 different Axelar create3 factory addresses

### ISSUE THREAD

**Issue by rube-de** [SKYBITDev3/SKYBIT-Keyless-Deployment#4]
At https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment?tab=readme-ov-file#axelar
 you mention the factory is will be deployed at `0x8cf037a598957EFE440841E256f4CA0056A8219C`
 and later https://github.com/SKYBITDev3/SKYBIT-Keyless-Deployment?tab=readme-ov-file#using-an-already-deployed-create2-factory-to-deploy-a-create3-factory
 you say it's deployed at `0x6513Aedb4D1593BA12e50644401D976aebDc90d8`

Is the difference because of keyless vs create2 deployer?
Maybe including a hint for this would be helpful

**Comment by SKYBITDev3** [comment]
`0x6513Aedb4D1593BA12e50644401D976aebDc90d8` is the address of Axelar's CREATE3 factory that Axelar deployed themself using their own CREATE2 factory (at `0x98b2920d53612483f91f12ed7754e51b4a77919e`, which I believe was deployed "normally" from an EOA i.e. CREATE EVM opcode behind the scenes).

You can see these addresses published on their web site at:
https://docs.axelar.dev/resources/contract-addresses/mainnet#evm-contract-addresses
https://docs.axelar.dev/resources/contract-addresses/testnet#evm-contract-addresses

`0x8cf037a598957EFE440841E256f4CA0056A8219C` is the address you'd get if you deploy Axelar's CREATE3 factory yourself **keylessly** using the scripts that I've provided and with the current EVM version and settings.

So the difference in address is the result of the different methods of deploying the same contract code.
